steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pengaduan-frontend", "./frontend"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pengaduan-frontend"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - pengaduan-frontend
      - --image=gcr.io/$PROJECT_ID/pengaduan-frontend
      - --platform=managed
      - --region=asia-southeast2
      - --allow-unauthenticated
      - --port=8080
images:
  - gcr.io/$PROJECT_ID/pengaduan-frontend
